src/Text/Email/Parser.hs, src/Text/Email/Validate.hs, tests/Main.hs
They were broken and it was driving me crazy
=> Fix read instance and read test

email-validate.cabal, src/Text/Email/Parser.hs, src/Text/Email/Validate.hs, stack.yaml
Needed this for database stuff where we know that if it got inserted, it was already validated. Can't make the types fit otherwise without introduce Identity/Maybe wrappers on the field and that's blehhhhhhhhh.
=> stack.yaml, export data constructors

email-validate.cabal
Per https://github.com/fpco/stackage/issues/3187
=> Bump QuickCheck upper bound to 2.12

email-validate.cabal
Per https://github.com/fpco/stackage/issues/3290
=> Bump doctest upper bound to 0.15

CHANGELOG.md, email-validate.cabal
=> Allow use of doctest 0.15

CHANGELOG.md, email-validate.cabal
=> Allow use of hspec 2.5

email-validate.cabal
Addressing https://github.com/commercialhaskell/stackage/issues/3763
=> Bump doctest upper bound to 0.17

email-validate.cabal
Addressing https://github.com/commercialhaskell/stackage/issues/3949
=> Allow QuickCheck-2.12, bump version to 2.3.2.7

CHANGELOG.md, email-validate.cabal
Addressing https://github.com/commercialhaskell/stackage/pull/4139
=> Bump HSpec upper bound

.travis.yml, stack.yaml
Add LTS 12 & 13 to build matrix.
=> Update supported Stackage LTSes

email-validate.cabal
Addressing https://github.com/commercialhaskell/stackage/issues/4444
=> Allow QuickCheck 2.13

email-validate.cabal
Builds fine and all tests pass.
=> Allow QuickCheck 2.14

email-validate.cabal
All tests pass here. Fixes #58
=> Allow template-haskell 2.17

email-validate.cabal
=> Allow doctest 0.17

email-validate.cabal
=> Allow hspec 2.8

email-validate.cabal
Builds fine and all tests pass.
=> Allow attoparsec 0.14

email-validate.cabal
=> Allow doctest 0.18

email-validate.cabal
Builds fine and all tests pass.
=> Allow doctest 0.20

email-validate.cabal
Builds fine and all tests pass.
=> Allow hspec 2.10

email-validate.cabal
@Porges 
Builds and tests fine. Please consider making a Hackage release for easier packaging.
Resolves #69
=> Bump template-haskell dependency
